### ISSUE TITLE
Homework week 3

### ISSUE THREAD

**Issue by mogenshoj** [Sreelatha-Vallabhaneni/hyf-homework#2]
Very nice job! I'm don't have many comments, it looks very good

**Warmup**
Just a small thing, just so find something to comment on :)
```
//7.Create a function called runAfterDelay. It has two parameters: delay and callback. When called the function should wait delay seconds and then call the provided callback function. Try and call this function with different delays and different callback functions.
const runAfterDelay = (delay, callback) => setTimeout(callback, delay);
const func1 = () => {
    console.log('7. should be logged after 4 seconds');
}
runAfterDelay(4000, () => {func1()});
runAfterDelay(4800, () => {earthLogger()});
```

When the functions are just called inside another function, you could just pass them in directly:
```
runAfterDelay(4000, func1);
runAfterDelay(4800, earthLogger);
```

**Game**
Nice game, and very cool with adding the sound!! 👍 
Just some general feedback, it looks good - also the design!

When you have blocks like this:
```
  const setup = document.body.addEventListener("keypress", event => {
    if (event.keyCode === 115 && selectInput > 0 && timer > 0) {
      ...
```

You can make a little helper function to check this part `selectInput > 0 && timer > 0`, to make it more readable. So this could be:
```
const isGameRunning = () => selectInput > 0 && timer > 0;
const setup = document.body.addEventListener("keypress", event => {
  if (event.keyCode === 115 && isGameRunning()) {
      ...
```
This way the function name is more readable, and the check can be re-used multiple times.

**hyfBay**
Perfect, good job 👍

**Comment by chklueter** [comment]
@mogenshoj nice feedback :) Well done @Sreelatha-Vallabhaneni for a perfect hyfbay ;)

**Comment by Sreelatha-Vallabhaneni** [comment]
hi @mogenshoj 
Thanks for your nice feedback, I made changes based on your feedback and updated them.
thank you @chklueter
