### ISSUE TITLE
JS2 Week 2 Feedback

### ISSUE THREAD

**Issue by orhantoy** [Sreelatha-Vallabhaneni/hyf-homework#3]
@Sreelatha-Vallabhaneni :v:

## Warmup array exercises / Doubling of number

https://github.com/Sreelatha-Vallabhaneni/hyf-homework/blob/14f852e01b44a91c1c20f3e0e6643172ffa0c46c/javascript/javascript2/week2/doubling-of-numbers.js#L7

Very nice implementation here. Only minor thing is that the const name could be more descriptive if it was named something like `doubledOddNumbers`. Having `filter` in the name makes it sound like it is a filter function.

## Warmup array exercises / Working with movies

- Awesome with the use of reduce 💪 I would have used this as the solution as it is more optimized than filtering and taking the length of the result.
    https://github.com/Sreelatha-Vallabhaneni/hyf-homework/blob/14f852e01b44a91c1c20f3e0e6643172ffa0c46c/javascript/javascript2/week2/movies/mvs2.js#L13
- Nice that you're copying movie, otherwise you would modify the original movies.
    https://github.com/Sreelatha-Vallabhaneni/hyf-homework/blob/14f852e01b44a91c1c20f3e0e6643172ffa0c46c/javascript/javascript2/week2/movies/mvs2.js#L17
- Exercise 7 is not entirely correct. The exercise is to "create an array of movies where a word in the title is duplicated". I would suggest you first create a separate function that can detect if a given sentence contains duplicate words. Then you can go ahead and use that function in a `filter`. Feel free to ask questions in here if you need more guidance/hints.
    https://github.com/Sreelatha-Vallabhaneni/hyf-homework/blob/14f852e01b44a91c1c20f3e0e6643172ffa0c46c/javascript/javascript2/week2/movies/mvs2.js#L44-L52
- I have a general comment on the way you use `console.log`. For instance ``console.log(`4. Tag Key :`, extraKeyTag);`` does work but you don't need to use the back-ticks as you are not doing string interpolation. So either I would use string interpolation like
  ```
  console.log(`4. Tag Key : ${extraKeyTag}`)
  ```
  or instead do
  ```
  console.log("4. Tag Key :", extraKeyTag)
  ```

I don't have much feedback as you have done a great job here.

## hyfBay - get the okay'est products here - continued

Nice work on this, I like the vibrant colors 👩‍🎨 

https://github.com/Sreelatha-Vallabhaneni/hyf-homework/blob/14f852e01b44a91c1c20f3e0e6643172ffa0c46c/javascript/javascript2/week2/hyfBay/main.js#L29-L39

Your implementation works and does the job. Here's some feedback on minor ways to improve it:

- Instead of doing `searchInput.value.toLowerCase().trim()` for every iteration you could move this out of the `filter` and only do it once.
- `searchValue` isn't the best name here. Something like `filteredProducts` or `productsMatchingSearch` would be a bit more descriptive.

**Comment by Sreelatha-Vallabhaneni** [comment]
Hi Orhan toy,
Thanks for your feedback and I will improve my solutions as per your
guidance thank you!

Regards,
Sreelatha Vallabhaneni.

**Comment by orhantoy** [comment]
@Sreelatha-Vallabhaneni Updated with hyfBay feedback :v:

**Comment by orhantoy** [comment]
@Sreelatha-Vallabhaneni Just a reminder to address the feedback :v:

Mainly I would like you to look into Exercise 7 (Movies, duplicated title). When that is done please ping me in here and I'll mark your homework as approved.

**Comment by Sreelatha-Vallabhaneni** [comment]
Hi @orhantoy ,
I updated exercise 7 (Movies, duplicated title), please review it.
thank you!

**Comment by orhantoy** [comment]
Awesome @Sreelatha-Vallabhaneni! 🎉 
Marking your assignment as approved ✅
